import "./globals.css";
import "@heathmont/moon-themes-tw/lib/moon.css";
import { cookies } from "next/headers";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = cookies().get("theme")?.value || "light";
  return (
    <html lang="en" dir="ltr" className={`theme-moon-${theme} font-averta`}>
      <body>{children}</body>
    </html>
  );
}
